### ISSUE TITLE
Refactor code generation and update process

### ISSUE THREAD

**Issue by almarklein** [pygfx/wgpu-py#139]
Issue to track a series of tasks/PRs to make the code-generation easier and better defined, so that upgrading to newer versions of wpgu-native and the WebGPU spec become easier.

In particular, we want to:
*  Untangle how we use the IDL (webgpu spec) and headerfile. Instead, we use the IDL to generate the public API, and the header file to help write low-level calls. And maybe validate them. Only "match" them for generating enum mappings.
* Don't parse the headerfile ourselves, but get the the required info from cffi.
* Implement the codegen in smaller pieces that are easier to understand and test.
* Better document the update-process.

Tasks:
* [x] #135 implement code-patching for the API (IDL -> base API -> backends). Notes:
* [x] #143 Refactor `rs` backend into multiple files.
* [x] #143 Generate enums and flags from IDL.
* [x] #144 Improve the generated type annotations.
* [x] #145 Header parsing (via cfffi) and implement new workflow from updating to changes in the headerfile.
* [x] Delete or revive `help()` function for using during maintenance.
* [x]  #149 Delete or revive codegen report.
* [x] #152 Consider putting `configure_swap_chain` on the canvas.
* [x] #153 We define properties that WebGPU does not define. Either remove or `@apidiff.add` them.
* [x] #154 Update to latest WebGPU
* [x] Update to latest wgpu-native

**Comment by Korijn** [comment]
I think this is a good idea:

> Consider putting configure_swap_chain on the canvas.

I think it's best to strictly separate wrappers from utilities.

**Comment by almarklein** [comment]
> We define properties that WebGPU does not define

I don't see why WebGPU lists attributes like buffer size and usage as "internal slots" but not as public attributes. The gfx-rs library also does not seem to have them.
